const { Post } =  require('../models');

const postinfo = [
    {
        title: 'My trip to Dubai',
        city: 'Burj Khalifa',
        state_province: 'Dubai',
        country: 'UAE',
        image_name: 'burjkhalifadubai.jpg',
        description:'skdmci asndakni caesiu dcnakksn cai lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        restaurants:'loyola',
        attractions:'Dubai Experience Tour',
        meal_cost:'$$$',
        hotel_cost:'$$$',
        tips:'siiacbaiuc aihwsbcaixna iaybsyab',
        kid_friendly:'yes',
        pet_friendly:'no',
        safety_rating:'Be Mindful',
        user_id:'1',
    },
    {
        title: 'The pink Sea',
        location:'Galerazamba',
        city: 'Galerazamba',
        state_province: '',
        country: 'Colombia',
        image_name: 'galerazambacolombia.jpg',
        description:'hsbiachb dbhwabdx wscv yqwdb lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        restaurants:'Seaside Seafood',
        attractions:'Colombian Museum',
        meal_cost:'$$',
        hotel_cost:'$',
        tips:'asdix iuew iuwedbi iaesdip iqw',
        kid_friendly:'yes',
        pet_friendly:'yes',
        safety_rating:'Pack a Gun',
        user_id:'2',
    },
    {
        title: 'Trip to Spain',
        city: 'Spain',
        state_province: '',
        country: 'Barcelona',
        image_name: 'barcelonaspain.jpg',
        description:'dsjai cbhdixi buiasb xi lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        restaurants:'Ichiraku Ramen',
        attractions:'Mt. Fuji',
        meal_cost:'$$$',
        hotel_cost:'$$',
        tips:'jsna iuuedbsaci yasgxi ',
        kid_friendly:'yes',
        pet_friendly:'yes',
        safety_rating:'safe',
        user_id:'3',
    },
    {
        title: 'How we lost our money',
        city: 'Las Vegas',
        state_province: 'Nevada',
        country: 'USA',
        image_name: 'lasvegasnevada.jpg',
        description:'csdh ewucb  iuheds i bcwhascbi lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        restaurants:'SOHO japanese restaurant',
        attractions:'Las Vegas Casino',
        meal_cost:'$$$$',
        hotel_cost:'$$$$',
        tips:'aisuhd aisuc b ihabsi ',
        kid_friendly:'no',
        pet_friendly:'no',
        safety_rating:'Pack a Gun',
        user_id:'4',
    },
    {
        title: 'Greece Trip',
        city: 'Athens',
        state_province: '',
        country: 'Greece',
        image_name: 'athensgreece.jpg',
        description:'sdvc svy csauci  jwhsvwcuy asjchv lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        restaurants:'Kolonaki',
        attractions:'Heritage Museum',
        meal_cost:'$$',
        hotel_cost:'$$$',
        tips:'cdah abuid xiasd kajsdb iwh',
        kid_friendly:'yes',
        pet_friendly:'yes',
        safety_rating:'safe',
        user_id:'1',
    },
    {
        title: 'Oui Oui',
        city: 'Paris',
        state_province: '',
        country: 'France',
        image_name: 'parisfrance.jpg',
        description:'sdvc svy csauci  jwhsvwcuy asjchv lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        restaurants:'Chihuahua Town',
        attractions:'Eiffel Tower',
        meal_cost:'$$',
        hotel_cost:'$$$',
        tips:'cdah abuid xiasd kajsdb iwh',
        kid_friendly:'yes',
        pet_friendly:'yes',
        safety_rating:'safe',
        user_id:'3',
    },
    {
        title: 'Swiss Chocolate',
        city: 'Zuric',
        state_province: '',
        country: 'Switzerland',
        image_name: 'swissalpsswitzerland.jpg',
        description:'sdvc svy csauci  jwhsvwcuy asjchv lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        restaurants:'Chihuahua Town',
        attractions:'Eiffel Tower',
        meal_cost:'$$',
        hotel_cost:'$$$',
        tips:'cdah abuid xiasd kajsdb iwh',
        kid_friendly:'no',
        pet_friendly:'yes',
        safety_rating:'safe',
        user_id:'2',
    },
];

const seedPosts = () => Post.bulkCreate(postinfo);

module.exports = seedPosts;
