const { Post } =  require('../models');

const postinfo = [
{
    title: 'My trip to Dubai',
    location:'Burj Khalifa, Dubai',
    description:'skdmci asndakni caesiu dcnakksn cai',
    restaurants:'loyola',
    attractions:'Dubai Experience Tour',
    meal_cost:'$$$',
    hotel_cost:'$$$',
    tips:'siiacbaiuc aihwsbcaixna iaybsyab',
    kid_friendly:'yes',
    pet_friendly:'no',
    safety_rating:'Be Mindful',
    user_id:'1',
},
{
    title: 'The pink Sea',
    location:'Galerazamba, Colombia',
    description:'hsbiachb dbhwabdx wscv yqwdb ',
    restaurants:'Seaside Seafood',
    attractions:'Colombian Museum',
    meal_cost:'$$',
    hotel_cost:'$',
    tips:'asdix iuew iuwedbi iaesdip iqw',
    kid_friendly:'yes',
    pet_friendly:'yes',
    safety_rating:'Pack a Gun',
    user_id:'2',
},
{
    title: 'Trip to Japan',
    location:'Mt. Fuji, Japan',
    description:'dsjai cbhdixi buiasb xi',
    restaurants:'Ichiraku Ramen',
    attractions:'Mt. Fuji',
    meal_cost:'$$$',
    hotel_cost:'$$',
    tips:'jsna iuuedbsaci yasgxi ',
    kid_friendly:'yes',
    pet_friendly:'yes',
    safety_rating:'safe',
    user_id:'3',
},
{
    title: 'How we lost our money',
    location:'Las Vegas, Nevada',
    description:'csdh ewucb  iuheds i bcwhascbi ',
    restaurants:'SOHO japanese restaurant',
    attractions:'Las Vegas Casino',
    meal_cost:'$$$$',
    hotel_cost:'$$$$',
    tips:'aisuhd aisuc b ihabsi ',
    kid_friendly:'no',
    pet_friendly:'no',
    safety_rating:'Pack a Gun',
    user_id:'4',
},
{
    title: 'Greece Trip',
    location:'Athens, Greece',
    description:'sdvc svy csauci  jwhsvwcuy asjchv ',
    restaurants:'Kolonaki',
    attractions:'Heritage Museum',
    meal_cost:'$$',
    hotel_cost:'$$$',
    tips:'cdah abuid xiasd kajsdb iwh',
    kid_friendly:'yes',
    pet_friendly:'yes',
    safety_rating:'safe',
    user_id:'1',
},

];

const seedPosts = () => Post.bulkCreate(postinfo);

module.exports = seedPosts;
